server:
  port: 8301

spring:
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: rbac
        password: 1234
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: RBAC-Gateway

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://rbac:1234@localhost:8001/register/eureka/
zuul:
  SendErrorFilter:
    error:
      disable: true
  routes:
    auth:
      # \u6240\u6709\u4EE5/auth\u5F00\u5934\u7684\u8BF7\u6C42\u90FD\u4F1A\u88AB\u8F6C\u53D1\u5230\u540D\u79F0\u4E3AFEBS-Auth\u7684\u670D\u52A1\u4E0A
      path: /auth/**
      serviceId: RBAC-Auth
      # \u8868\u793A\u4E0D\u8FC7\u6EE4\u8BF7\u6C42\u5934\u4FE1\u606F\uFF0C\u5373\u8BF7\u6C42\u7684\u8BF7\u6C42\u5934\u4FE1\u606F\u5C06\u539F\u5C01\u4E0D\u52A8\u7684\u8F6C\u53D1\u51FA\u53BB
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: RBAC-Server-System
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: RBAC-Server-Test
      sensitiveHeaders: "*"

  # \u8BBE\u7F6E\u4E3Atrue\u65F6\uFF0C\u8868\u793A\u5F00\u542F\u91CD\u8BD5\u673A\u5236\uFF1B
  retryable: true
  # \u8868\u793A\u5173\u95ED\u6240\u6709\u9ED8\u8BA4\u8DEF\u7531\u914D\u7F6E\u89C4\u5219
  ignored-services: "*"
  ribbon:
    eager-load:
      # \u8BBE\u7F6E\u4E3Atrue\u7684\u65F6\u5019\u8868\u793A\u5F00\u542FRibbon\u7684\u9965\u997F\u52A0\u8F7D\u6A21\u5F0F\uFF0C\u5373\u5728\u5E94\u7528\u542F\u52A8\u7684\u65F6\u5019\u5C31\u53BB\u83B7\u53D6\u76F8\u5E94\u7684Client\u5907\u7528\u3002
      enabled: true

ribbon:
  # \u8BBE\u7F6E\u8BF7\u6C42\u8D85\u65F6\u65F6\u95F4\uFF0C\u5355\u4F4D\u4E3A\u6BEB\u79D2
  ReadTimeout: 3000

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

  #  spring.boot.admin.client.url指定了SBA服务端地址；
  #  spring.boot.admin.client.username对应SBA服务端的用户名；
  #  spring.boot.admin.client.password对应SBA服务端的密码；
  #  info.**配置了SBA客户端的名称，描述和版本信息；
  #  management.endpoints.web.exposure.include='*'表示将SBA客户端的所有监控端点都暴露给SBA服务端；
  #  management.endpoint.health.show-details表示总是展示详细的健康信息。