server:
  port: 8001
  servlet:
    context-path: /register

spring:
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: rbac
        password: 1234
  application:
    name: RBAC-Register
  security:
    user:
      name: rbac
      password: 1234

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

#  spring.boot.admin.client.url指定了SBA服务端地址；
#  spring.boot.admin.client.username对应SBA服务端的用户名；
#  spring.boot.admin.client.password对应SBA服务端的密码；
#  info.**配置了SBA客户端的名称，描述和版本信息；
#  management.endpoints.web.exposure.include='*'表示将SBA客户端的所有监控端点都暴露给SBA服务端；
#  management.endpoint.health.show-details表示总是展示详细的健康信息。

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
