# \u5E94\u7528\u7AEF\u53E3\u53F7\u4E3A8201\uFF0C\u670D\u52A1\u540D\u79F0\u4E3ARBAC-Server-System
server:
  port: 8201

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: RBAC-Server-System

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://rbac:1234@localhost:8001/register/eureka/
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      # user-info-uri
      # \u8DEF\u5F84\u4E3Ahttp://localhost:8301/auth/user\uFF0C\u901A\u8FC7\u5FAE\u670D\u52A1\u7F51\u5173\uFF0C
      # \u8BE5\u8BF7\u6C42\u5C06\u88AB\u8F6C\u53D1\u5230http://localhost:8101/user\u3002
      # \u8BE5\u914D\u7F6E\u7684\u4F5C\u7528\u4E3B\u8981\u6709\u4E24\u4E2A\uFF1A
      # \u5230\u8BA4\u8BC1\u670D\u52A1\u5668\u91CC\u6821\u9A8C\u5F53\u524D\u8BF7\u6C42\u5934\u4E2D\u7684\u4EE4\u724C\u662F\u5426\u4E3A\u5408\u6CD5\u7684\u4EE4\u724C\uFF1B
      # \u901A\u8FC7\u5F53\u524D\u4EE4\u724C\u83B7\u53D6\u5BF9\u5E94\u7684\u7528\u6237\u4FE1\u606F\u3002
      user-info-uri: http://localhost:8301/auth/user